#!/bin/bash -e
#(C)Code by Solaris Eco 2020
#Blog:https://edges5352.github.io
#Email:bluebreeze191@gamil.com
#GitHub:EdgeS5352 (Solaris Eco)
#coding:UTF-8


#some path
export output="/dev/null"
export import_list="$PREFIX/etc/coraph"


#some color
red="\033[31m"
green="\033[32m"
suffix="\033[0m"


#import some argument
if [ -f $import_list ]; then
  export ubuntu=`sed -n "3,3p" $PREFIX/etc/coraph.conf`
  export arch=`sed -n "6,6p" $PREFIX/etc/coraph.conf`
  export fedora=`sed -n "9,9p" $PREFIX/etc/coraph.conf`
  export centos=`sed -n "12,12p" $PREFIX/etc/coraph.conf`
  export debian=`sed -n "15,15p" $PREFIX/etc/coraph.conf`
  export kali=`sed -n "18,18p" $PREFIX/etc/coraph.conf`
else
  echo "${red} $import_list does not exist! ${suffix}"
  exit "2"

#some tips
export version="0.6"
export download_tip="echo -e ${green}Downloading Rootfs,this may take some time...${suffix}"
export void_error="echo -e ${red}Please input a effective argument!${suffix}"
export unpack_tip="echo -e ${green}Unpacking,please waiting...${suffix}"


#some links
export ubuntu_link="wget ${ubuntu} -O ~/ubuntu.tar.xz"
export arch_link="wget ${arch} -O ~/arch.tar.xz"
export fedora_link="wget ${fedora} -O ~/fedora.tar.xz"
export centos_link="wget ${centos} -O ~/centos.tar.xz"
export debian_link="wget ${debian} -O ~/debian.tar.xz"
export kali_link="wget ${kali} -O ~/kali.tar.xz"


#do you have proot?
proot=`which proot`
if [ x"$proot" = x ]
  echo "${green} Installing proot... ${suffix}"
  apt install proot -y 1>"$output" 2>&1


#start determine
case $1 in
"deploy")
  case $2 in
  "ubuntu")
  ${download_tip}
  ${ubuntu_link}
  ;;  
  "arch")
  ${download_tip}
  ${arch_link}
  ;;
  "fedora")
  ${download_tip}
  ${fedora_link}
  ;;
  "centos")
  ${download_tip}
  ${centos_link}
  ;;
  "debian")
  ${download_tip}
  ${debian_link}
  ;;
  "kali")
  ${download_tip}
  ${kali_link}
  ;;
  "*")
  ${void_error}
  exit 1
  esac
  mkdir $PREFIX/etc/.cora 1>"$output" 2>&1
  mv $2.tar.xz $PREFIX/etc/.cora/
  cd $PREFIX/etc/.cora/
  ${unpack_tip}
  xz -d $2.tar.xz
  tar -xvf $2.tar
  rm $PREFIX/etc/.cora/$2.tar
  cd $PREFIX/bin
  touch $2
  

