#!/bin/bash -e
#(C)Code by Solaris Eco 2020
#Blog:https://edges5352.github.io
#Email:bluebreeze191@gamil.com
#GitHub:EdgeS5352 (Solaris Eco)
#coding:UTF-8


#some path
export bin="$PREFIX/bin/"
export output="/dev/null/"
export import_list="$PREFIX/etc/coraph.conf"
export base="~/coraph/"

#some color
red="\033[31m"
green="\033[32m"
suffix="\033[0m"


#import some argument
if [ -f $import_list ]; then
  export ubuntu=`sed -n "3,3p" $import_list`
  export arch=`sed -n "6,6p" $import_list`
  export fedora=`sed -n "9,9p" $import_list`
  export centos=`sed -n "12,12p" $import_list`
  export debian=`sed -n "15,15p" $import_list`
  export kali=`sed -n "18,18p" $import_list`
else
  echo "${red} $import_list does not exist! ${suffix}"
  exit "2"

#some tips
export version="0.6"
export download_tip="echo -e ${green}Downloading Rootfs,this may take some time...${suffix}"
export void_error="echo -e ${red}Please input a effective argument!${suffix}"
export unpack_tip="echo -e ${green}Unpacking,please waiting...${suffix}"


#some links
export ubuntu_link="wget ${ubuntu} -O ~/ubuntu.tar.xz"
export arch_link="wget ${arch} -O ~/arch.tar.xz"
export fedora_link="wget ${fedora} -O ~/fedora.tar.xz"
export centos_link="wget ${centos} -O ~/centos.tar.xz"
export debian_link="wget ${debian} -O ~/debian.tar.xz"
export kali_link="wget ${kali} -O ~/kali.tar.xz"


#do you have proot?
proot=`which proot`
if [ x"$proot" = x ]
  echo "${green} Installing proot... ${suffix}"
  apt install proot -y 1>"$output" 2>&1
fi

#start determine
case $1 in
"deploy")
  case $2 in
  "ubuntu")
  ${download_tip}
  ${ubuntu_link}
  ;;  
  "arch")
  ${download_tip}
  ${arch_link}
  ;;
  "fedora")
  ${download_tip}
  ${fedora_link}
  ;;
  "centos")
  ${download_tip}
  ${centos_link}
  ;;
  "debian")
  ${download_tip}
  ${debian_link}
  ;;
  "kali")
  ${download_tip}
  ${kali_link}
  ;;
  "*")
  ${void_error}
  exit "2"
  esac
  

  #Global setting
  mkdir ~/.coraph 1>"$output" 2>&1
  mv $2.tar.xz ~/.coraph/
  cd ~/.coraph/
  ${unpack_tip}
  xz -d $2.tar.xz
  tar -xvf $2.tar
  echo "${green} Start to remove compression package..."
  rm ~/.coraph/$2.tar
  echo "${green} Write launch script in $bin$2 ${suffix}"
  cd $PREFIX/bin
  touch $2
  

  #Write script
  dir="~/.coraph/$2"
  cat > $bin$2 <<- EOM
  #!/bin/bash -e
  cd $(dirname $0)
    unset LD_PRELOAD
    command="proot"
    command+=" --link2symlink"
    command+=" -0"
    command+=" -r $dir"
    command+=" -b /dev"
    command+=" -b /proc"
    command+=" -b $dir/root:/dev/shm"
    command+=" -b /sdcard"
    command+=" -w /root"
    command+=" /usr/bin/env -i"
    command+=" HOME=/root"
    command+=" PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games"
    command+=" TERM=$TERM"
    command+=" LANG=zh_CN.UTF-8"
    command+=" /bin/bash --login"
    com="$@"
    if [ -z "$1" ];then
      exec $command
    else
      $command -c "$com"
    fi
    EOM
  chmod +x $bin$2
  echo "${green} Process done,now you can launch $2 with command [$2] ${suffix}"
  exit "0"
;;
"remove")
  echo "${red} Start to remove $2... ${suffix}"
  if [ x"$2" == x ]; then
    ${void_error}
    exit "2"
  fi
  if [ -f "$base$2" ]
    rm -rf $base$2
  else
    echo "${red} You didn't install $2! ${suffix}"
  fi
  rm -rf $bin$2
  
